### ISSUE TITLE
Review 1

### ISSUE THREAD

**Issue by tshemsedinov** [EugeneSemivolos/LetsThrowDice#2]
- Duplicate code: https://github.com/EugeneSemivolos/LetsThrowDice/blob/a935b35aff36faafaa94246c105b002bc5de592d/scripts/main.js#L35-L54
- Use eslint, prettier
- You can google how to get element index in `for..of` loop: https://github.com/EugeneSemivolos/LetsThrowDice/blob/a935b35aff36faafaa94246c105b002bc5de592d/scripts/main.js#L72-L76
- Magic numbers in all codebase, for example: https://github.com/EugeneSemivolos/LetsThrowDice/blob/a935b35aff36faafaa94246c105b002bc5de592d/scripts/main.js#L94-L95
- Decompose long function, use collections of metadata or collections of functions https://github.com/EugeneSemivolos/LetsThrowDice/blob/a935b35aff36faafaa94246c105b002bc5de592d/scripts/main.js#L125-L151
- Try to decompose nested loops
- Don't commit `.idea` to repo

**Comment by YevheniiSemyvolos** [comment]
Thanks for reviewing! All of this is fixed
